format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipBerkeleyApi}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_BSD_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipBerkeleyApi, value: '256'}
  - type: Integer
    attributes: {id: TCPIP_BSD_MAX_BSD_SOCKETS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
- type: ElementPosition
  attributes: {x: '620', y: '20', id: tcpipBerkeleyApi}
